management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int} # unique id for app instances registered with eureka